package com.jtouzy.cv.model.classes;

import com.jtouzy.dao.annotations.DAOTable;
import com.jtouzy.dao.annotations.DAOTableField;
import com.jtouzy.dao.annotations.DAOTableRelation;
import com.jtouzy.dao.db.DBType;

@DAOTable(tableName = "chp")
public class Championship {
	@DAOTableField(id = true, autoGenerated = true, name = "numchp", required = true, type = DBType.INTEGER)
	private Integer identifier;
	@DAOTableRelation(
		column = @DAOTableField(name = "cmpchp", required = true, type = DBType.INTEGER),
		relationColumn = "numcmp"
	)
	private Competition competition;
	@DAOTableField(name = "libchp", length = 40, required = true, type = DBType.VARCHAR)
	private String label;
	@DAOTableField(name = "genchp", length = 1, required = true, type = DBType.ENUM)
	private Championship.Gender gender;
	@DAOTableField(name = "ordchp", type = DBType.INTEGER)
	private Integer order;
	@DAOTableField(name = "typchp", length = 3, required = true, type = DBType.ENUM)
	private Championship.Type type;
	@DAOTableField(name = "stachp", length = 1, required = true, type = DBType.ENUM)
	private Championship.State state;
	
	public Integer getIdentifier() {
		return identifier;
	}
	public void setIdentifier(Integer identifier) {
		this.identifier = identifier;
	}
	public Competition getCompetition() {
		return competition;
	}
	public void setCompetition(Competition competition) {
		this.competition = competition;
	}
	public String getLabel() {
		return label;
	}
	public void setLabel(String label) {
		this.label = label;
	}
	public Championship.Gender getGender() {
		return gender;
	}
	public void setGender(Championship.Gender gender) {
		this.gender = gender;
	}
	public Integer getOrder() {
		return order;
	}
	public void setOrder(Integer order) {
		this.order = order;
	}
	public Championship.Type getType() {
		return type;
	}
	public void setType(Championship.Type type) {
		this.type = type;
	}
	public Championship.State getState() {
		return state;
	}
	public void setState(Championship.State state) {
		this.state = state;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Championship [identifier=");
		builder.append(identifier);
		builder.append(", competition=");
		builder.append(competition);
		builder.append(", label=");
		builder.append(label);
		builder.append(", gender=");
		builder.append(gender);
		builder.append(", order=");
		builder.append(order);
		builder.append(", type=");
		builder.append(type);
		builder.append(", state=");
		builder.append(state);
		builder.append("]");
		return builder.toString();
	}

	public enum Gender {
		M, X, F
	}
	public enum Type {
		CHP, CUP
	}
	public enum State {
		C, V 
	}
}
