package com.jtouzy.cv.model.classes;

import java.time.LocalDateTime;

import com.jtouzy.dao.annotations.DAOTable;
import com.jtouzy.dao.annotations.DAOTableField;
import com.jtouzy.dao.db.DBType;

@DAOTable(tableName = "cmt")
public class Comment {
	@DAOTableField(id = true, autoGenerated = true, name = "numcmt", required = true, type = DBType.INTEGER)
	private Integer identifier;
	@DAOTableField(name = "entcmt", length = 3, required = true, type = DBType.ENUM)
	private Comment.Entity entity;
	@DAOTableField(name = "valcmt", required = true, type = DBType.INTEGER)
	private Integer entityValue;
	@DAOTableField(name = "usrcmt", required = true, type = DBType.INTEGER)
	private Integer user;
	@DAOTableField(name = "datcmt", required = true, type = DBType.DATETIME)
	private LocalDateTime date;
	@DAOTableField(name = "txtcmt", length = 4000, required = true, type = DBType.VARCHAR)
	private String content;
	
	public Integer getIdentifier() {
		return identifier;
	}
	public void setIdentifier(Integer identifier) {
		this.identifier = identifier;
	}
	public Comment.Entity getEntity() {
		return entity;
	}
	public void setEntity(Comment.Entity entity) {
		this.entity = entity;
	}
	public Integer getEntityValue() {
		return entityValue;
	}
	public void setEntityValue(Integer entityValue) {
		this.entityValue = entityValue;
	}
	public Integer getUser() {
		return user;
	}
	public void setUser(Integer user) {
		this.user = user;
	}
	public LocalDateTime getDate() {
		return date;
	}
	public void setDate(LocalDateTime date) {
		this.date = date;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Comment [identifier=");
		builder.append(identifier);
		builder.append(", entity=");
		builder.append(entity);
		builder.append(", entityValue=");
		builder.append(entityValue);
		builder.append(", user=");
		builder.append(user);
		builder.append(", date=");
		builder.append(date);
		builder.append(", content=");
		builder.append(content);
		builder.append("]");
		return builder.toString();
	}

	public enum Entity {
		NWS, MAT
	}
}
