package com.jtouzy.cv.model.classes;

import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.jtouzy.dao.annotations.DAOTable;
import com.jtouzy.dao.annotations.DAOTableField;
import com.jtouzy.dao.db.DBType;

@DAOTable(tableName = "cmt")
public class Comment {
	@DAOTableField(id = true, autoGenerated = true, name = "numcmt", type = DBType.INTEGER)
	private Integer identifier;
	@DAOTableField(name = "entcmt", type = DBType.ENUM)
	@NotNull(message = "L'entité doit être renseignée")
	@Size(max = 3, message = "La taille de l'entité doit être au maximum de {max}")
	private Comment.Entity entity;
	@DAOTableField(name = "valcmt", type = DBType.INTEGER)
	@NotNull(message = "La valeur de l'entité doit être renseignée")
	private Integer entityValue;
	@DAOTableField(name = "usrcmt", type = DBType.INTEGER)
	@NotNull(message = "L'utilisateur doit être renseigné")
	private Integer user;
	@DAOTableField(name = "datcmt", type = DBType.DATETIME)
	@NotNull(message = "La date doit être renseignée")
	private LocalDateTime date;
	@DAOTableField(name = "txtcmt", type = DBType.VARCHAR)
	@NotNull(message = "Le commentaire doit être renseigné")
	@Size(max = 4000, message = "La taille du commentaire doit être au maximum de {max}")
	private String content;
	
	public Integer getIdentifier() {
		return identifier;
	}
	public void setIdentifier(Integer identifier) {
		this.identifier = identifier;
	}
	public Comment.Entity getEntity() {
		return entity;
	}
	public void setEntity(Comment.Entity entity) {
		this.entity = entity;
	}
	public Integer getEntityValue() {
		return entityValue;
	}
	public void setEntityValue(Integer entityValue) {
		this.entityValue = entityValue;
	}
	public Integer getUser() {
		return user;
	}
	public void setUser(Integer user) {
		this.user = user;
	}
	public LocalDateTime getDate() {
		return date;
	}
	public void setDate(LocalDateTime date) {
		this.date = date;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Comment [identifier=");
		builder.append(identifier);
		builder.append(", entity=");
		builder.append(entity);
		builder.append(", entityValue=");
		builder.append(entityValue);
		builder.append(", user=");
		builder.append(user);
		builder.append(", date=");
		builder.append(date);
		builder.append(", content=");
		builder.append(content);
		builder.append("]");
		return builder.toString();
	}

	public enum Entity {
		NWS, MAT
	}
}
