package com.jtouzy.cv.model.classes;

import com.jtouzy.dao.annotations.DAOTable;
import com.jtouzy.dao.annotations.DAOTableField;
import com.jtouzy.dao.annotations.DAOTableRelation;
import com.jtouzy.dao.db.DBType;

@DAOTable(tableName = "cmp")
public class Competition {
	@DAOTableField(id = true, autoGenerated = true, name = "numcmp", required = true, type = DBType.INTEGER)
	private Integer identifier;
	@DAOTableRelation(
		column = @DAOTableField(name = "saicmp", required = true, type = DBType.INTEGER), relationColumn = "numsai"
	)	
	private Season season;
	@DAOTableField(name = "cvtcmp", required = true, type = DBType.BOOLEAN)
	private boolean cvt;
	@DAOTableField(name = "libcmp", length = 40, required = true, type = DBType.VARCHAR)
	private String label;
	@DAOTableField(name = "dsccmp", length = 4000, type = DBType.VARCHAR)
	private String description;
	@DAOTableField(name = "ordcmp", required = true, type = DBType.INTEGER)
	private Integer order;
	@DAOTableField(name = "liecmp", length = 80, type = DBType.VARCHAR)
	private String cvtCity;
	@DAOTableField(name = "datcmp", length = 6, type = DBType.VARCHAR)
	private String cvtDate;
	@DAOTableField(name = "latcmp", length = 50, type = DBType.VARCHAR)
	private String cvtLatitude;
	@DAOTableField(name = "lngcmp", length = 50, type = DBType.VARCHAR)
	private String cvtLongitude;
	@DAOTableField(name = "etacmp", length = 1, type = DBType.VARCHAR)
	private String state;
	@DAOTableField(name = "rgpcmp", type = DBType.INTEGER)
	private Integer groupNumber;
	
	public Integer getIdentifier() {
		return identifier;
	}
	public void setIdentifier(Integer identifier) {
		this.identifier = identifier;
	}
	public Season getSeason() {
		return season;
	}
	public void setSeason(Season season) {
		this.season = season;
	}
	public boolean isCvt() {
		return cvt;
	}
	public void setCvt(boolean cvt) {
		this.cvt = cvt;
	}
	public String getLabel() {
		return label;
	}
	public void setLabel(String label) {
		this.label = label;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Integer getOrder() {
		return order;
	}
	public void setOrder(Integer order) {
		this.order = order;
	}
	public String getCvtCity() {
		return cvtCity;
	}
	public void setCvtCity(String cvtCity) {
		this.cvtCity = cvtCity;
	}
	public String getCvtDate() {
		return cvtDate;
	}
	public void setCvtDate(String cvtDate) {
		this.cvtDate = cvtDate;
	}
	public String getCvtLatitude() {
		return cvtLatitude;
	}
	public void setCvtLatitude(String cvtLatitude) {
		this.cvtLatitude = cvtLatitude;
	}
	public String getCvtLongitude() {
		return cvtLongitude;
	}
	public void setCvtLongitude(String cvtLongitude) {
		this.cvtLongitude = cvtLongitude;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	public Integer getGroupNumber() {
		return groupNumber;
	}
	public void setGroupNumber(Integer groupNumber) {
		this.groupNumber = groupNumber;
	}
	
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Competition [identifier=");
		builder.append(identifier);
		builder.append(", season=");
		builder.append(season);
		builder.append(", cvt=");
		builder.append(cvt);
		builder.append(", label=");
		builder.append(label);
		builder.append(", description=");
		builder.append(description);
		builder.append(", order=");
		builder.append(order);
		builder.append(", cvtCity=");
		builder.append(cvtCity);
		builder.append(", cvtDate=");
		builder.append(cvtDate);
		builder.append(", cvtLatitude=");
		builder.append(cvtLatitude);
		builder.append(", cvtLongitude=");
		builder.append(cvtLongitude);
		builder.append(", state=");
		builder.append(state);
		builder.append(", groupNumber=");
		builder.append(groupNumber);
		builder.append("]");
		return builder.toString();
	}
}
