package com.jtouzy.cv.model.classes;

import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.jtouzy.dao.annotations.DAOTable;
import com.jtouzy.dao.annotations.DAOTableField;
import com.jtouzy.dao.annotations.DAOTableRelation;
import com.jtouzy.dao.db.DBType;

@DAOTable(tableName = "cmp")
public class Competition {
	@DAOTableField(id = true, autoGenerated = true, name = "numcmp", type = DBType.INTEGER)
	private Integer identifier;
	@DAOTableRelation(
		column = @DAOTableField(name = "saicmp", type = DBType.INTEGER), relationColumn = "numsai"
	)	
	@NotNull(message = "La saison doit être renseignée")
	private Season season;
	@DAOTableField(name = "cvtcmp", type = DBType.BOOLEAN)
	@NotNull(message = "La zone 'CVT' doit être renseignée")
	private Boolean cvt;
	@DAOTableField(name = "libcmp", type = DBType.VARCHAR)
	@NotNull(message = "Le libellé doit être renseigné")
	@Size(max = 40, message = "La taille du libellé doit être au maximum de {max}")
	private String label;
	@DAOTableField(name = "dsccmp", type = DBType.VARCHAR)
	@Size(max = 4000, message = "La taille de la description doit être au maximum de {max}")
	private String description;
	@DAOTableField(name = "ordcmp", type = DBType.INTEGER)
	@NotNull(message = "L'ordre doit être renseigné")
	private Integer order;
	@DAOTableField(name = "liecmp", type = DBType.VARCHAR)
	@Size(max = 80, message = "La taille du lieu doit être au maximum de {max}")
	private String cvtCity;
	@DAOTableField(name = "datcmp", type = DBType.DATETIME)
	private LocalDateTime cvtDate;
	@DAOTableField(name = "latcmp", type = DBType.VARCHAR)
	@Size(max = 50, message = "La taille de la latitude doit être au maximum de {max}")
	private String cvtLatitude;
	@DAOTableField(name = "lngcmp", type = DBType.VARCHAR)
	@Size(max = 50, message = "La taille de la longitude doit être au maximum de {max}")
	private String cvtLongitude;
	@DAOTableField(name = "etacmp", type = DBType.ENUM)
	@Size(max = 1, message = "La taille de l'état doit être au maximum de {max}")
	private Competition.State state;
	@DAOTableField(name = "rgpcmp", type = DBType.INTEGER)
	private Integer groupNumber;
	
	public Integer getIdentifier() {
		return identifier;
	}
	public void setIdentifier(Integer identifier) {
		this.identifier = identifier;
	}
	public Season getSeason() {
		return season;
	}
	public void setSeason(Season season) {
		this.season = season;
	}
	public Boolean isCvt() {
		return cvt;
	}
	public void setCvt(Boolean cvt) {
		this.cvt = cvt;
	}
	public String getLabel() {
		return label;
	}
	public void setLabel(String label) {
		this.label = label;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Integer getOrder() {
		return order;
	}
	public void setOrder(Integer order) {
		this.order = order;
	}
	public String getCvtCity() {
		return cvtCity;
	}
	public void setCvtCity(String cvtCity) {
		this.cvtCity = cvtCity;
	}
	public LocalDateTime getCvtDate() {
		return cvtDate;
	}
	public void setCvtDate(LocalDateTime cvtDate) {
		this.cvtDate = cvtDate;
	}
	public String getCvtLatitude() {
		return cvtLatitude;
	}
	public void setCvtLatitude(String cvtLatitude) {
		this.cvtLatitude = cvtLatitude;
	}
	public String getCvtLongitude() {
		return cvtLongitude;
	}
	public void setCvtLongitude(String cvtLongitude) {
		this.cvtLongitude = cvtLongitude;
	}
	public Competition.State getState() {
		return state;
	}
	public void setState(Competition.State state) {
		this.state = state;
	}
	public Integer getGroupNumber() {
		return groupNumber;
	}
	public void setGroupNumber(Integer groupNumber) {
		this.groupNumber = groupNumber;
	}
	
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Competition [identifier=");
		builder.append(identifier);
		builder.append(", season=");
		builder.append(season);
		builder.append(", cvt=");
		builder.append(cvt);
		builder.append(", label=");
		builder.append(label);
		builder.append(", description=");
		builder.append(description);
		builder.append(", order=");
		builder.append(order);
		builder.append(", cvtCity=");
		builder.append(cvtCity);
		builder.append(", cvtDate=");
		builder.append(cvtDate);
		builder.append(", cvtLatitude=");
		builder.append(cvtLatitude);
		builder.append(", cvtLongitude=");
		builder.append(cvtLongitude);
		builder.append(", state=");
		builder.append(state);
		builder.append(", groupNumber=");
		builder.append(groupNumber);
		builder.append("]");
		return builder.toString();
	}
	
	public enum State {
		C, V
	}
}
