package com.jtouzy.cv.model.classes;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.jtouzy.dao.annotations.DAOTable;
import com.jtouzy.dao.annotations.DAOTableField;
import com.jtouzy.dao.db.DBType;

@DAOTable(tableName = "gym")
public class Gym {
	@DAOTableField(id = true, autoGenerated = true, name = "idegym", type = DBType.INTEGER)
	private Integer identifier;
	@DAOTableField(name = "libgym", type = DBType.VARCHAR)
	@NotNull(message = "Le libellé doit être renseigné")
	@Size(max = 40, message = "La taille du libellé doit être au maximum de {max}")
	private String label;
	
	public Integer getIdentifier() {
		return identifier;
	}
	public void setIdentifier(Integer identifier) {
		this.identifier = identifier;
	}
	public String getLabel() {
		return label;
	}
	public void setLabel(String label) {
		this.label = label;
	}
	
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Gym [identifier=");
		builder.append(identifier);
		builder.append(", label=");
		builder.append(label);
		builder.append("]");
		return builder.toString();
	}
}
