package com.jtouzy.cv.model.classes;

import java.time.LocalDateTime;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.jtouzy.dao.annotations.DAOTable;
import com.jtouzy.dao.annotations.DAOTableField;
import com.jtouzy.dao.annotations.DAOTableRelation;
import com.jtouzy.dao.db.DBType;

@DAOTable(tableName = "nws")
public class News {
	@DAOTableField(id = true, autoGenerated = true, name = "numnws", type = DBType.INTEGER)
	private Integer identifier;
	@DAOTableField(name = "titnws", type = DBType.VARCHAR)
	@NotNull(message = "Le titre doit être renseigné")
	@Size(max = 30, message = "La taille du titre doit être au maximum de {max}")
	private String title;
	@DAOTableField(name = "cntnws", type = DBType.VARCHAR)
	@NotNull(message = "Le contenu doit être renseigné")
	@Size(max = 4000, message = "La taille du contenu doit être au maximum de {max}")
	private String content;
	@DAOTableRelation(
		column = @DAOTableField(name = "autnws", type = DBType.INTEGER),
		relationColumn = "numusr"
	)
	@NotNull(message = "L'auteur doit être renseigné")
	private User author;
	@DAOTableField(name = "dcrnws", type = DBType.DATETIME)
	@NotNull(message = "La date de création doit être renseignée")
	private LocalDateTime creationDate;
	@DAOTableField(name = "dpunws", type = DBType.DATETIME)
	private LocalDateTime publishDate;
	@DAOTableField(name = "stanws", type = DBType.ENUM)
	@NotNull(message = "L'état doit être renseigné")
	private News.State state;
	
	public Integer getIdentifier() {
		return identifier;
	}
	public void setIdentifier(Integer identifier) {
		this.identifier = identifier;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public User getAuthor() {
		return author;
	}
	public void setAuthor(User author) {
		this.author = author;
	}
	public LocalDateTime getCreationDate() {
		return creationDate;
	}
	public void setCreationDate(LocalDateTime creationDate) {
		this.creationDate = creationDate;
	}
	public LocalDateTime getPublishDate() {
		return publishDate;
	}
	public void setPublishDate(LocalDateTime publishDate) {
		this.publishDate = publishDate;
	}
	public News.State getState() {
		return state;
	}
	public void setState(News.State state) {
		this.state = state;
	}

	public enum State {
		C, V
	}
}
