package com.jtouzy.cv.model.classes;

import com.jtouzy.dao.annotations.DAOTable;
import com.jtouzy.dao.annotations.DAOTableField;
import com.jtouzy.dao.annotations.DAOTableIDField;

@DAOTable(tableName = "sai")
public class Season {
	@DAOTableIDField(autoGenerated = true)
	@DAOTableField(fieldName = "numsai")
	private Integer identifier;
	@DAOTableField(fieldName = "prdsai")
	private String startYear;
	@DAOTableField(fieldName = "prfsai")
	private String endYear;

	public Integer getIdentifier() {
		return identifier;
	}

	public void setIdentifier(Integer identifier) {
		this.identifier = identifier;
	}

	public String getStartYear() {
		return startYear;
	}

	public void setStartYear(String startYear) {
		this.startYear = startYear;
	}

	public String getEndYear() {
		return endYear;
	}

	public void setEndYear(String endYear) {
		this.endYear = endYear;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Season [getIdentifier()=");
		builder.append(getIdentifier());
		builder.append(", getStartYear()=");
		builder.append(getStartYear());
		builder.append(", getEndYear()=");
		builder.append(getEndYear());
		builder.append("]");
		return builder.toString();
	}
}
