package com.jtouzy.cv.model.classes;

import java.time.LocalDate;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.jtouzy.dao.annotations.DAOTable;
import com.jtouzy.dao.annotations.DAOTableField;
import com.jtouzy.dao.db.DBType;

@DAOTable(tableName = "usr")
public class User {
	@DAOTableField(id = true, autoGenerated = true, name = "numusr", type = DBType.INTEGER)
	private Integer identifier;
	@DAOTableField(name = "maiusr", type = DBType.VARCHAR)
	@Size(max = 100, message = "La taille de l'e-mail doit être au maximum de {max}")
	private String mail;
	@DAOTableField(name = "nomusr", type = DBType.VARCHAR)
	@NotNull(message = "Le nom doit être renseigné")
	@Size(max = 50, message = "La taille du nom doit être au maximum de {max}")
	private String name;
	@DAOTableField(name = "preusr", type = DBType.VARCHAR)
	@NotNull(message = "Le prénom doit être renseigné")
	@Size(max = 50, message = "La taille du prénom doit être au maximum de {max}")
	private String firstName;
	@DAOTableField(name = "pwdusr", type = DBType.VARCHAR)
	@Size(max = 130, message = "La taille du mot de passe doit être au maximum de {max}")
	private String password;
	@DAOTableField(name = "dnsusr", type = DBType.DATE)
	private LocalDate birthDate;
	@DAOTableField(name = "telusr", type = DBType.VARCHAR)
	@Size(max = 20, message = "La taille du nom doit être au maximum de {max}")
	private String phone;
	@DAOTableField(name = "admusr", type = DBType.BOOLEAN)
	@NotNull(message = "La zone 'Administrateur' doit être renseignée")
	private Boolean administrator;
	
	public Integer getIdentifier() {
		return identifier;
	}
	public void setIdentifier(Integer identifier) {
		this.identifier = identifier;
	}
	public String getMail() {
		return mail;
	}
	public void setMail(String mail) {
		this.mail = mail;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public LocalDate getBirthDate() {
		return birthDate;
	}
	public void setBirthDate(LocalDate birthDate) {
		this.birthDate = birthDate;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public Boolean isAdministrator() {
		return administrator;
	}
	public void setAdministrator(Boolean administrator) {
		this.administrator = administrator;
	}
	
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("User [identifier=");
		builder.append(identifier);
		builder.append(", mail=");
		builder.append(mail);
		builder.append(", name=");
		builder.append(name);
		builder.append(", firstName=");
		builder.append(firstName);
		builder.append(", password=");
		builder.append(password);
		builder.append(", birthDate=");
		builder.append(birthDate);
		builder.append(", phone=");
		builder.append(phone);
		builder.append(", administrator=");
		builder.append(administrator);
		builder.append("]");
		return builder.toString();
	}
}
